### ISSUE TITLE
Improve Settings

### ISSUE THREAD

**Issue by TwrFyr** [TwrFyr/n-henpy#27]
### todo
- [ ] add directory choosers to settings
  - [ ] dir chooser uses absolute path, if that path can not be found -> use relative default path once
- [ ] make application use the settings (centralized data manager)
- [ ] generalise `DirectorySettingsFrame` with `StringSettingsFrame`

### dod
Settings for the following points exist:
- [ ] default folder for downloads
- [ ] default folder for favorites
- [ ] number of threads for downloading
- [ ] wait time between downloading entries when downloading favorites
Additionally:
- [ ] settings must be persisted over application restart
